### ISSUE TITLE
Ignore code blocks in Markdown files when using auto-format

### ISSUE THREAD

**Issue by wassimk** [andrewferrier/wrapping.nvim#31]
I discovered this plugin while trying to figure out how to use auto-format for text paragraphs while ignoring code blocks.

When I have this enabled, wrapping is done automatically, and it's lovely. But it also wraps in ``` code blocks.

``` lua
vim.opt_local.formatoptions:append('a')
```

Could I use this plugin to ignore code blocks in Markdown files but still have it auto-format?

**Comment by andrewferrier** [comment]
@wassimk Sorry for the delay in responding. I don't know an easy way to do that, unfortunately, given NeoVim capabilities as they exist today. AFAIK, `wrap` is a global capability across an entire buffer. That said, `wrapping.nvim` does already ignore code blocks when *calculating* whether wrapping should be turned on or off. If you perform your re-formatting using an external formatter (e.g. I use `remark`, through `null-ls`) that might do what you want, but for now I think that's outside the scope of `wrapping.nvim`.
