### ISSUE TITLE
Is it possible to set custom max width?

### ISSUE THREAD

**Issue by Demianeen** [andrewferrier/wrapping.nvim#37]
I usually have a nvim on full screen, and when I open Markdown, my line rarely wraps because of this. Is it possible to set the max width before wrap to 100 for example instead of the window length?

**Comment by andrewferrier** [comment]
Not easily, I believe. wrapping.nvim relies on inbuilt NeoVim capability to do soft wrapping, and I don't think it's possible to set a different margin for that than window width. I'll keep this issue open to take a more detailed look sometime. Thanks for your interest!

**Comment by andrewferrier** [comment]
I had a look at this. I don't think such an option exists. You can use `wrapmargin` when `textwidth=0` to force where hard wrapping should occur relative to the right-edge of the window, but that's not quite what you were asking for, I think.

I think this probably needs an issue on NeoVim itself. For now, I'll close this issue.

**Comment by Demianeen** [comment]
Thanks for pointing, just [did it](https://github.com/neovim/neovim/discussions/28221)
