### ISSUE TITLE
Command not available after installation.

### ISSUE THREAD

**Issue by wxguy** [andrewferrier/wrapping.nvim#38]
The file I am working on is `asciidoc`.  I am using the following default as mentioned in the doc:-

```
require("lazy").setup({
    {
        "andrewferrier/wrapping.nvim",
        config = function()
            require("wrapping").setup()
        end
    },
}
```

This works fine as per key binding `[ow` to enable soft-wrap mode.  I would like to link this with my own key binding. Hence I wanted to try the provided command `SoftWrapMode`. This has given me an error `Not an Editor Command: SoftWrapMode`. 

Is it intended or am I doing something wrong?

**Comment by andrewferrier** [comment]
@wxguy I'm not sure why you're seeing the error you're seeing, but I would just link it directly to the lua function instead:

```
return {
    url = "git@github.com:andrewferrier/wrapping.nvim",
    config = function()
        require("wrapping").setup({
            create_keymaps = false,
        })

        vim.keymap.set("n", "<leader>s", function()
            require("wrapping").soft_wrap_mode()
        end, {})
    end,
}
```

See the help/README for the other lua function names. Hope that helps. Obviously, remove `create_keymaps` if you still want the default keymaps to be created as well.

**Comment by andrewferrier** [comment]
Closed since I don't think there's a bug here.
