### ISSUE TITLE
Wrap only code comments

### ISSUE THREAD

**Issue by nianiam** [andrewferrier/wrapping.nvim#40]
It would be great if the plugin were able to hard wrap code comment lines in filetypes normally ignored. In theory you could toggle on/off hard wrapping based on the treesitter node currently selected, however, I have no idea what the performance implications are.

**Comment by andrewferrier** [comment]
@nianiam hi, it's definitely an interesting idea, I agree! And I think it could work, I'm not sure of the perf implications either although gut feel tells me it wouldn't be a problem.

Just to set your expectations, I think it's unlikely I'll be able to work on this any time soon. But I'll keep the issue open in case anyone else wants to contribute a patch or discuss the feature request.

Thanks for your idea and hope you still enjoy using wrapping.nvim!

**Comment by andrewferrier** [comment]
OK, I've thought about this one; unfortunately I just don't think this is going to work in NeoVim as currently implemented. The `wrap` option is global to a file; if you change it between soft and hard wrapping, it makes display changes to the entire file immediately. There is - as far as I know - no way to limit it to only part of a file.

I think resolving this would involve significant changes to NeoVim itself, which I think is out of the scope of this plugin and the time I have. But if folks want to raise this with NeoVim directly, I'd be interested in building support into this plugin if such a capability did become available.

Thanks for your thoughts!
