### ISSUE TITLE
Newbie question: how to make line at bottom don't show at once?

### ISSUE THREAD

**Issue by xzbdmw** [andrewferrier/wrapping.nvim#41]
https://github.com/andrewferrier/wrapping.nvim/assets/97848247/0defa083-5992-45a9-83f5-b7dac4021dce

like this video, even though I bind j to gj, I surely can jump by virtual line, but once my cursor is at bottom and reach my scolloff setting, a *whole* soft wrapped line come in display, which make my cursor jump here and there, is there a way to accomplish this that I can jump one virtual line at bottom?

**Comment by andrewferrier** [comment]
I'm not aware of a way to do this in NeoVim without a change to NeoVim itself, sorry.
