### ISSUE TITLE
Add typst files to auto_set_mode_filetype_allowlist

### ISSUE THREAD

**Issue by ruimp** [andrewferrier/wrapping.nvim#42]
Typst is gaining some traction as a LaTeX alternative. It would be nice to add ".typ" files to the allow list. Thank you.

**Comment by ruimp** [comment]
I don't really understand how this works. When I search  `:h filetype` locally, I can't find a mention of filetype associated to ".typ".
However, on the online [documentation](https://neovim.io/doc/user/filetype.html) there is a mention to ".typ" filetypes in the list. Maybe it's being introduced?
On my system it detect filetype "typst", but I use the plugin [typst.nvim](https://github.com/kaarmu/typst.vim).
Thanks for your work on this brilliant plugin.

**Comment by andrewferrier** [comment]
Hi, OK, so I looked into this. As of NeoVim 0.10+ (unreleased, so this is currently nightly-only), `typst` files are automatically supported; so I've added support for them to `wrapping.nvim`. This will only work out of the box on NeoVim 0.10+.

If you're using an earlier version of NeoVim, you should be able to add a `typst` filetype manually using this in your NeoVim config:

```
vim.filetype.add({
    extension = {
        typ = "typst"
    }
})
```
